### ISSUE TITLE
Failed to save regression model

### ISSUE THREAD

**Issue by SeanWangJS** [oracle/tribuo#67] opened 2020-10-20 06:20 UTC
[Describe]

Get [java.io.NotSerializableException: org.tribuo.regression.ImmutableRegressionInfo$$Lambda$32/187472540] exception when write regression model to file.

[Reproduce]

1. load data
        CSVLoader<Regressor> loader = new CSVLoader<>(new RegressionFactory());
        ListDataSource<Regressor> ds = loader.loadDataSource(Paths.get("D:/data/Datasets/winequality-red.csv"), "y");
        MutableDataset<Regressor> dataset = new MutableDataset<>(ds);
2. train model
        LibLinearRegressionTrainer trainer = new LibLinearRegressionTrainer();
        Model<Regressor> model = trainer.train(dataset);
3. save model to file
        ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("D:/data/winequality-red.model"));
        out.writeObject(model);

[Expected behaviour]

No exception

[Exception Stack]
java.io.NotSerializableException: org.tribuo.regression.ImmutableRegressionInfo$$Lambda$303/0x0000000800c1c710

	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1193)
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1387)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
	at java.base/java.util.TreeSet.writeObject(TreeSet.java:502)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1196)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1523)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1579)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1444)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:353)
	at org.tribuo.regression.liblinear.LibLinearRegressionModelTest.test(LibLinearRegressionModelTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

[System]
 - OS: Windows
 - Java Version: 8
 - JDK Vendor: [Oracle

[Suggestion]
Add [transient] keyword to [domain] field in ImmutableRegressionInfo class

**Comment by jhalexand** [comment] 2020-10-20 13:31
Thanks for reporting this, we'll take a look. One issue unrelated to this bug that you'll run into is that you don't have quite the parameters for loading the Wine Quality dataset. Since the winequality-red.csv is actually semicolon-separated, you'll need to give that as an argument to the CSVLoader (look back at the [Regression tutorial](https://tribuo.org/learn/4.0/tutorials/regression-tribuo-v4.html)). Once it is loaded properly, you'll also need to make sure to specify the column name for the response (output) variable in this dataset, which is the one named `quality`, so you'll want to provide that rather than `y`.

But, back to the issue at hand, a little extra info for tracking this down.  Here's the debug output from trying to serialize that regression model:

```
	- element of array (index: 0)
	- array (class "[Ljava.lang.Object;", size: 1)
	- field (class "java.lang.invoke.SerializedLambda", name: "capturedArgs", type: "class [Ljava.lang.Object;")
	- object (class "java.lang.invoke.SerializedLambda", SerializedLambda[capturingClass=interface java.util.Comparator, functionalInterfaceMethod=java/util/Comparator.compare:(Ljava/lang/Object;Ljava/lang/Object;)I, implementation=invokeStatic java/util/Comparator.lambda$comparing$77a9974f$1:(Ljava/util/function/Function;Ljava/lang/Object;Ljava/lang/Object;)I, instantiatedMethodType=(Ljava/lang/Object;Ljava/lang/Object;)I, numCaptured=1])
	- custom writeObject data (class "java.util.TreeSet")
	- object (class "java.util.TreeSet", [DIM-0=3.0])
	- field (class "java.util.Collections$UnmodifiableCollection", name: "c", type: "interface java.util.Collection")
	- object (class "java.util.Collections$UnmodifiableSortedSet", [DIM-0=3.0])
	- field (class "org.tribuo.regression.ImmutableRegressionInfo", name: "domain", type: "interface java.util.Set")
	- object (class "org.tribuo.regression.ImmutableRegressionInfo", MultipleRegressionOutput({name=DIM-0,id=0,count=1119,maxMap=8.000000,min=3.000000,mean=5.647006,variance=0.652565}))
	- field (class "org.tribuo.Model", name: "outputIDInfo", type: "interface org.tribuo.ImmutableOutputInfo")
	- root object (class "org.tribuo.regression.liblinear.LibLinearRegressionModel", liblinear-regression-model - Model(class-name=org.tribuo.common.liblinear.LibLinearModel,dataset=Dataset(class-name=org.tribuo.MutableDataset,datasource=SplitDataSourceProvenance(className=org.tribuo.evaluation.TrainTestSplitter,innerSourceProvenance=CSV(class-name=org.tribuo.data.csv.CSVLoader,outputFactory=OutputFactory(class-name=org.tribuo.regression.RegressionFactory,splitChar=,),response-name=quality,separator=;,quote=",path=file:/tmp/winequality-red.csv,file-modified-time=2020-10-20T08:55:16.662-04:00,resource-hash=SHA-256[4A402CF041B025D4566D954C3B9BA8635A3A8A01E039005D97D6A710278CF05E]),trainProportion=0.699999988079071,seed=0,size=1599,isTrain=true),transformations=[],is-sequence=false,is-dense=false,num-examples=1119,num-features=11,num-outputs=1,tribuo-version=4.0.1),trainer=Trainer(class-name=org.tribuo.regression.liblinear.LibLinearRegressionTrainer,epsilon=0.1,maxIterations=1000,cost=1.0,terminationCriterion=0.1,trainerType=LibLinearType(class-name=org.tribuo.regression.liblinear.LinearRegressionType,type=L2R_L2LOSS_SVR,host-short-name=LibLinearType),train-invocation-count=0,is-sequence=false,host-short-name=Trainer),trained-at=2020-10-20T09:17:44.567732-04:00,instance-values={},tribuo-version=4.0.1))
```

**Comment by Craigacp** [comment] 2020-10-20 15:43
We'll put out a 4.0.2 point release with the fix for this and several other small fixes in the near future. Thanks for reporting.

**Closed** 2020-10-20 15:42 UTC
Labels: bug
